name: CI

on: [push]

jobs:
  linting:
    runs-on: ${{matrix.os}}

    strategy:
      matrix: 
        os: [ubuntu-latest,windows-latest,macos-latest]
        version: ['3.9', '3.10']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Format code with black
        run: black app.py

      - name: Run flake8
        run: flake8 app.py
